version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: nest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nest-scaffold
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis-cache:
    image: redis:alpine
    container_name: nest-redis
    ports:
      - "6379:6379"
  nest-app:
    volumes:
      - ./uploads:/app/uploads  # 映射上传目录